heartbeat.monitors:


#Monitor all containers using an icmp ping
- type: icmp
  schedule: '*/5 * * * * * *'
  hosts: ["es01","es02","es03","kib01"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 3s
  wait: 1s


#Monitor the Elasticsearch instance.
- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["https://es01:9200", "https://es02:9200", "https://es03:9200"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 3s
  username: kibana_system
  password: YgYeTFJSwZZ2C3J8U4op
  check.request:
    method: "GET"
  check.response:
    status: 200


#Monitor the Kibana instance.
- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://kib01:5601"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 3s
  check.request:
    method: "GET"
  check.response:
    status: 200

##Monitor the nginx instance.
#- type: http
#  enabled: true
#  schedule: '@every 5s'
#  urls: ["http://nginx/server-status"]
#  ipv4: true
#  ipv6: true
#  mode: any
#  timeout: 3s
#  check.request:
#    method: "GET"
#  check.response:
#    status: 200
#
#
##Monitor the MySQL instance.
#- type: tcp
#  enabled: true
#  schedule: '@every 5s'
#  hosts: ["tcp://mysql:3306"]


processors:
- add_docker_metadata: ~


monitoring.enabled: true


output.elasticsearch:
  hosts: ["https://es01:9200"]
  protocol: "https"
  username: elastic
  password: fBfGcaS3NlToqhEBUJA6

#Use SSL settings for HTTPS.

  ssl.enabled: true

  ssl.certificate_authorities: ["/usr/share/elasticsearch/config/certificates/ca/ca.crt"]
  ssl.certificate: "/usr/share/elasticsearch/config/certificates/es01/es01.crt"
  ssl.key: "/usr/share/elasticsearch/config/certificates/es01/es01.key"




logging.to_files: false



#============================== Kibana =========================================
setup.kibana:
  host: "https://kib01:5601"
  username: elastic
  password: fBfGcaS3NlToqhEBUJA6
  setup.kibana.protocol: "https"
  setup.kibana.ssl.enabled: true
  setup.kibana.ssl.certificate_authorities: ["/usr/share/elasticsearch/config/certificates/ca/ca.crt"]
  setup.kibana.ssl.certificate: "/usr/share/elasticsearch/config/certificates/heart01/heart01.crt"
  setup.kibana.ssl.key: "/usr/share/elasticsearch/config/certificates/heart01/heart01.key"
  setup.kibana.ssl.verification_mode: none

  
#============================== Dashboards =====================================
# These settings control loading the sample dashboards to the Kibana index. Loading
# the dashboards is disabled by default and can be enabled either by setting the
# options here, or by using the `-setup` CLI flag.
setup.dashboards.enabled: true
